### ISSUE TITLE
Handle failure gracefully

### ISSUE THREAD

**Issue by markgaze** [benmatselby/precis#33]
Currently, if any service that Precis is connected to returns an error state, the whole process is killed. It would be nice if it could continue running until the service comes back online (or I quit to fix my config) as I might still be able to pull back GitHub PRs but not connect to Jenkins and I still want to see the PRs without restarting.

**Comment by benmatselby** [comment]
@markgaze Thanks for raising.. Hopefully this is now resolved, and you can continue to see data from services that can render.
